/* 
 * Streamr API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeployedProduct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeployedProductTests
    {
        // TODO uncomment below to declare an instance variable for DeployedProduct
        //private DeployedProduct instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeployedProduct
            //instance = new DeployedProduct();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeployedProduct
        /// </summary>
        [Test]
        public void DeployedProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeployedProduct
            //Assert.IsInstanceOfType<DeployedProduct> (instance, "variable 'instance' is a DeployedProduct");
        }


        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Test]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }
        /// <summary>
        /// Test the property 'BlockIndex'
        /// </summary>
        [Test]
        public void BlockIndexTest()
        {
            // TODO unit test for the property 'BlockIndex'
        }
        /// <summary>
        /// Test the property 'OwnerAddress'
        /// </summary>
        [Test]
        public void OwnerAddressTest()
        {
            // TODO unit test for the property 'OwnerAddress'
        }
        /// <summary>
        /// Test the property 'BeneficiaryAddress'
        /// </summary>
        [Test]
        public void BeneficiaryAddressTest()
        {
            // TODO unit test for the property 'BeneficiaryAddress'
        }
        /// <summary>
        /// Test the property 'PricePerSecond'
        /// </summary>
        [Test]
        public void PricePerSecondTest()
        {
            // TODO unit test for the property 'PricePerSecond'
        }
        /// <summary>
        /// Test the property 'PriceCurrency'
        /// </summary>
        [Test]
        public void PriceCurrencyTest()
        {
            // TODO unit test for the property 'PriceCurrency'
        }
        /// <summary>
        /// Test the property 'MinimumSubscriptionInSeconds'
        /// </summary>
        [Test]
        public void MinimumSubscriptionInSecondsTest()
        {
            // TODO unit test for the property 'MinimumSubscriptionInSeconds'
        }

    }

}
