/* 
 * Streamr API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Stream
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StreamTests
    {
        // TODO uncomment below to declare an instance variable for Stream
        //private Stream instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Stream
            //instance = new Stream();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Stream
        /// </summary>
        [Test]
        public void StreamInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Stream
            //Assert.IsInstanceOfType<Stream> (instance, "variable 'instance' is a Stream");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Test]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
        /// <summary>
        /// Test the property 'UiChannel'
        /// </summary>
        [Test]
        public void UiChannelTest()
        {
            // TODO unit test for the property 'UiChannel'
        }
        /// <summary>
        /// Test the property 'Partitions'
        /// </summary>
        [Test]
        public void PartitionsTest()
        {
            // TODO unit test for the property 'Partitions'
        }
        /// <summary>
        /// Test the property 'RequireSignedData'
        /// </summary>
        [Test]
        public void RequireSignedDataTest()
        {
            // TODO unit test for the property 'RequireSignedData'
        }
        /// <summary>
        /// Test the property 'RequireEncryptedData'
        /// </summary>
        [Test]
        public void RequireEncryptedDataTest()
        {
            // TODO unit test for the property 'RequireEncryptedData'
        }
        /// <summary>
        /// Test the property 'Inbox'
        /// </summary>
        [Test]
        public void InboxTest()
        {
            // TODO unit test for the property 'Inbox'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Test]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Test]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'AutoConfigure'
        /// </summary>
        [Test]
        public void AutoConfigureTest()
        {
            // TODO unit test for the property 'AutoConfigure'
        }
        /// <summary>
        /// Test the property 'StorageDays'
        /// </summary>
        [Test]
        public void StorageDaysTest()
        {
            // TODO unit test for the property 'StorageDays'
        }
        /// <summary>
        /// Test the property 'InactivityThresholdHours'
        /// </summary>
        [Test]
        public void InactivityThresholdHoursTest()
        {
            // TODO unit test for the property 'InactivityThresholdHours'
        }

    }

}
