/* 
 * Streamr API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateProduct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateProductTests
    {
        // TODO uncomment below to declare an instance variable for UpdateProduct
        //private UpdateProduct instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateProduct
            //instance = new UpdateProduct();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateProduct
        /// </summary>
        [Test]
        public void UpdateProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateProduct
            //Assert.IsInstanceOfType<UpdateProduct> (instance, "variable 'instance' is a UpdateProduct");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Streams'
        /// </summary>
        [Test]
        public void StreamsTest()
        {
            // TODO unit test for the property 'Streams'
        }
        /// <summary>
        /// Test the property 'PreviewStream'
        /// </summary>
        [Test]
        public void PreviewStreamTest()
        {
            // TODO unit test for the property 'PreviewStream'
        }
        /// <summary>
        /// Test the property 'PreviewConfigJson'
        /// </summary>
        [Test]
        public void PreviewConfigJsonTest()
        {
            // TODO unit test for the property 'PreviewConfigJson'
        }
        /// <summary>
        /// Test the property 'OwnerAddress'
        /// </summary>
        [Test]
        public void OwnerAddressTest()
        {
            // TODO unit test for the property 'OwnerAddress'
        }
        /// <summary>
        /// Test the property 'BeneficiaryAddress'
        /// </summary>
        [Test]
        public void BeneficiaryAddressTest()
        {
            // TODO unit test for the property 'BeneficiaryAddress'
        }
        /// <summary>
        /// Test the property 'PricePerSecond'
        /// </summary>
        [Test]
        public void PricePerSecondTest()
        {
            // TODO unit test for the property 'PricePerSecond'
        }
        /// <summary>
        /// Test the property 'PriceCurrency'
        /// </summary>
        [Test]
        public void PriceCurrencyTest()
        {
            // TODO unit test for the property 'PriceCurrency'
        }
        /// <summary>
        /// Test the property 'MinimumSubscriptionInSeconds'
        /// </summary>
        [Test]
        public void MinimumSubscriptionInSecondsTest()
        {
            // TODO unit test for the property 'MinimumSubscriptionInSeconds'
        }
        /// <summary>
        /// Test the property 'PendingChanges'
        /// </summary>
        [Test]
        public void PendingChangesTest()
        {
            // TODO unit test for the property 'PendingChanges'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'TermsOfUse'
        /// </summary>
        [Test]
        public void TermsOfUseTest()
        {
            // TODO unit test for the property 'TermsOfUse'
        }

    }

}
