/* 
 * Streamr API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DataunionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DataunionsApiTests
    {
        private DataunionsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DataunionsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataunionsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DataunionsApi
            //Assert.IsInstanceOfType(typeof(DataunionsApi), instance, "instance is a DataunionsApi");
        }

        
        /// <summary>
        /// Test DataunionsContractAddressJoinRequestsGet
        /// </summary>
        [Test]
        public void DataunionsContractAddressJoinRequestsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //string state = null;
            //instance.DataunionsContractAddressJoinRequestsGet(contractAddress, state);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressJoinRequestsJoinRequestIdDelete
        /// </summary>
        [Test]
        public void DataunionsContractAddressJoinRequestsJoinRequestIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //string joinRequestId = null;
            //instance.DataunionsContractAddressJoinRequestsJoinRequestIdDelete(contractAddress, joinRequestId);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressJoinRequestsJoinRequestIdGet
        /// </summary>
        [Test]
        public void DataunionsContractAddressJoinRequestsJoinRequestIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //string joinRequestId = null;
            //instance.DataunionsContractAddressJoinRequestsJoinRequestIdGet(contractAddress, joinRequestId);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressJoinRequestsJoinRequestIdPut
        /// </summary>
        [Test]
        public void DataunionsContractAddressJoinRequestsJoinRequestIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //string joinRequestId = null;
            //UpdateDataUnionJoinRequest body = null;
            //instance.DataunionsContractAddressJoinRequestsJoinRequestIdPut(contractAddress, joinRequestId, body);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressJoinRequestsPost
        /// </summary>
        [Test]
        public void DataunionsContractAddressJoinRequestsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //CreateDataUnionJoinRequest body = null;
            //instance.DataunionsContractAddressJoinRequestsPost(contractAddress, body);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressMembersGet
        /// </summary>
        [Test]
        public void DataunionsContractAddressMembersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //instance.DataunionsContractAddressMembersGet(contractAddress);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressMembersMemberAddressGet
        /// </summary>
        [Test]
        public void DataunionsContractAddressMembersMemberAddressGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //string memberAddress = null;
            //instance.DataunionsContractAddressMembersMemberAddressGet(contractAddress, memberAddress);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressSecretsDataUnionSecretIdDelete
        /// </summary>
        [Test]
        public void DataunionsContractAddressSecretsDataUnionSecretIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //string dataUnionSecretId = null;
            //instance.DataunionsContractAddressSecretsDataUnionSecretIdDelete(contractAddress, dataUnionSecretId);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressSecretsDataUnionSecretIdGet
        /// </summary>
        [Test]
        public void DataunionsContractAddressSecretsDataUnionSecretIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //string dataUnionSecretId = null;
            //var response = instance.DataunionsContractAddressSecretsDataUnionSecretIdGet(contractAddress, dataUnionSecretId);
            //Assert.IsInstanceOf<DataUnionSecret> (response, "response is DataUnionSecret");
        }
        
        /// <summary>
        /// Test DataunionsContractAddressSecretsDataUnionSecretIdPut
        /// </summary>
        [Test]
        public void DataunionsContractAddressSecretsDataUnionSecretIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //string dataUnionSecretId = null;
            //Body body = null;
            //var response = instance.DataunionsContractAddressSecretsDataUnionSecretIdPut(contractAddress, dataUnionSecretId, body);
            //Assert.IsInstanceOf<DataUnionSecret> (response, "response is DataUnionSecret");
        }
        
        /// <summary>
        /// Test DataunionsContractAddressSecretsGet
        /// </summary>
        [Test]
        public void DataunionsContractAddressSecretsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //instance.DataunionsContractAddressSecretsGet(contractAddress);
            
        }
        
        /// <summary>
        /// Test DataunionsContractAddressSecretsPost
        /// </summary>
        [Test]
        public void DataunionsContractAddressSecretsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //CreateDataUnionSecret body = null;
            //var response = instance.DataunionsContractAddressSecretsPost(contractAddress, body);
            //Assert.IsInstanceOf<DataUnionSecret> (response, "response is DataUnionSecret");
        }
        
        /// <summary>
        /// Test DataunionsContractAddressStatsGet
        /// </summary>
        [Test]
        public void DataunionsContractAddressStatsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractAddress = null;
            //instance.DataunionsContractAddressStatsGet(contractAddress);
            
        }
        
    }

}
