/* 
 * Streamr API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubscriptionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SubscriptionsApiTests
    {
        private SubscriptionsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SubscriptionsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubscriptionsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SubscriptionsApi
            //Assert.IsInstanceOfType(typeof(SubscriptionsApi), instance, "instance is a SubscriptionsApi");
        }

        
        /// <summary>
        /// Test SubscriptionsGet
        /// </summary>
        [Test]
        public void SubscriptionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SubscriptionsGet();
            //Assert.IsInstanceOf<List<Subscription>> (response, "response is List<Subscription>");
        }
        
        /// <summary>
        /// Test SubscriptionsPost
        /// </summary>
        [Test]
        public void SubscriptionsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateSubscription body = null;
            //instance.SubscriptionsPost(body);
            
        }
        
    }

}
